/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Coordinates { 'latitude' : number, 'longitude' : number }
export type Theme = { 'dark' : null } |
  { 'light' : null };
export interface UserConfig {
  'theme' : Theme,
  'contactName' : string,
  'whatsapp' : string,
}
export interface UserProfile {
  'theme' : Theme,
  'contactName' : string,
  'whatsapp' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'generateAlertMessage' : ActorMethod<[Coordinates], string>,
  'getAboutPage' : ActorMethod<[], string>,
  'getAllUserConfigs' : ActorMethod<[], Array<UserConfig>>,
  'getAllUserConfigsByTheme' : ActorMethod<[], Array<UserConfig>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserConfig' : ActorMethod<[], UserConfig>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveUserConfig' : ActorMethod<[UserConfig], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];